### ISSUE TITLE
Not an issue, more of a question actually.

### ISSUE THREAD

**Issue by markotitel** [bcongdon/bpy_lambda#14]
Hi,

I am trying run all commands from Dockerfile but not running `docker build`.
Just set up this on a VPS local system.

I hoped it will work for compiling `blender-headless` but came to the error which I can't resolve for couple of days now.
I was building Blender successfully `v2.79b` on Ubuntu system. Amazon Linux just "won't work".
What I want to achieve is build blender-headless binary and run it in Lambda with `os.system('./blender')` approach.

I am guessing that I miss some libraries. THe error I am getting when trying to `install_deps.sh` is 
 ```
Generating testsuite/runtest.py
llvm_ops.cpp:101:10: fatal error: 'iostream' file not found
```
`ERROR! OpenShadingLanguage-1.7.5 failed to compile, exiting`

I have updated GCC version to `9.3` but still getting the error.

Could you point me in the right direction please?

**Comment by bcongdon** [comment]
Which version of Amazon Linux are you using? I think that has made a difference in the past

**Comment by markotitel** [comment]
Thanks for taking time.
I am trying to build on Amazon Linux 2

**Comment by bcongdon** [comment]
Have you tried getting it to work on Amazon Linux 2018.03? https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/
